# Generated by Django 4.2.6 on 2023-11-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobster', '0003_alter_administrator_adminname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('degree', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('graduation_year', models.CharField(max_length=4)),
                ('skills', models.TextField()),
                ('spoken_languages', models.TextField()),
                ('job_experience', models.TextField()),
                ('personal_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
