# Generated by Django 4.2.6 on 2023-11-15 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobster', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobster.user'),
            preserve_default=False,
        ),
    ]
