# Generated by Django 4.2.6 on 2023-11-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobster', '0006_resume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
