# Generated by Django 4.2.6 on 2023-11-16 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobster', '0007_remove_resume_id_remove_resume_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cid',
            field=models.AutoField(default=None, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='gstin',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='postjob',
            fields=[
                ('jid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('jtitle', models.CharField(max_length=255)),
                ('jlocation', models.IntegerField()),
                ('jtype', models.CharField(max_length=255)),
                ('jskills', models.TextField()),
                ('jexperience', models.TextField()),
                ('jvacancies', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobster.company')),
            ],
        ),
    ]
