# Generated by Django 4.2.6 on 2023-11-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobster', '0011_remove_postjob_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='jlocation',
            field=models.CharField(max_length=100),
        ),
    ]
