# Generated by Django 4.1.3 on 2023-11-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobster', '0012_alter_postjob_jlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='cid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jobster.company'),
            preserve_default=False,
        ),
    ]
