# Generated by Django 4.2.6 on 2023-11-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobster', '0014_cprofile_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cprofile',
            name='cid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='cid',
            field=models.IntegerField(),
        ),
    ]
