# Generated by Django 4.2.6 on 2023-11-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobster', '0015_alter_cprofile_cid_alter_postjob_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('jid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobster.postjob')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobster.resume')),
            ],
        ),
    ]
